######################################################################
# Automatically generated by qmake (3.0) ?? ?? 5 01:09:47 2016
######################################################################

TEMPLATE = app
TARGET = MVCTest

TRANSLATIONS+=cn.ts

INCLUDEPATH += .
QT += widgets
QT  += xml
# Input
HEADERS += widget.h \
    controldelegate.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp \
    controldelegate.cpp
